# Generated by Django 3.1 on 2020-09-24 19:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('blog', '0011_auto_20200924_2205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tt',
            new_name='Profile',
        ),
    ]
