# Generated by Django 3.1 on 2020-09-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('blog', '0016_auto_20200924_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('browserfingerprint', models.CharField(max_length=64)),
                ('bf_uniquenes', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
